config/routes.rb
Ontology::Application.routes.draw do
  get "home/main"

  resources :tags

  resources :concepts

  root :to => 'concepts#index'

end

app/models/tag.rb
class Tag < ActiveRecord::Base
  attr_accessible :name, :no_text, :prompt, :yes_text
  
  has_many :taggings


  has_many :askables
  has_many :askers, :through=>:askables, :source=>:concept
  
  def self.options
    select("id,name").order("name ASC").collect{|e|[e.name,e.id]}
  end
  
  def self.reference_or_create_by_name( name )
    if name.blank?
      nil
    else
      a = where("lower(name) = ?", name.downcase)
      if a.size > 0
        a[0]
      else
        create(:name=>name)
      end
    end
  end
  
  # gives the tag a score to represent how useful it is for narrowing a given differential
  # higher is better
  def discernability( concepts )
    concept_ids = concepts.collect{|e|e.id}
    taggings = self.taggings.where(concept_id: concept_ids)
    original_size = concepts.size * 1.0
    
    size_a = original_size - taggings.select{|e|e.rules_out_if==true}.size
    size_b = original_size - taggings.select{|e|e.rules_out_if==false}.size
    
    score_a = size_a==0 ? 1.0 : size_a / original_size
    score_b = size_b==0 ? 1.0 : size_b / original_size
    
    1.0 - (score_a ** 2+score_b ** 2)/2.0
  end
  
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
  # GET /tags
  # GET /tags.json
  def index
    @tags = Tag.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @tags }
    end
  end

  # GET /tags/1
  # GET /tags/1.json
  def show
    @tag = Tag.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @tag }
    end
  end

  # GET /tags/new
  # GET /tags/new.json
  def new
    @tag = Tag.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @tag }
    end
  end

  # GET /tags/1/edit
  def edit
    @tag = Tag.find(params[:id])
  end

  # POST /tags
  # POST /tags.json
  def create
    @tag = Tag.new(params[:tag])

    respond_to do |format|
      if @tag.save
        format.html { redirect_to @tag, notice: 'Tag was successfully created.' }
        format.json { render json: @tag, status: :created, location: @tag }
      else
        format.html { render action: "new" }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /tags/1
  # PUT /tags/1.json
  def update
    @tag = Tag.find(params[:id])

    respond_to do |format|
      if @tag.update_attributes(params[:tag])
        format.html { redirect_to @tag, notice: 'Tag was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @tag.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tags/1
  # DELETE /tags/1.json
  def destroy
    @tag = Tag.find(params[:id])
    @tag.destroy

    respond_to do |format|
      format.html { redirect_to tags_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_form.html.erb
<%= form_for(@tag) do |f| %>
  <% if @tag.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tag.errors.count, "error") %> prohibited this tag from being saved:</h2>

      <ul>
      <% @tag.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :prompt %><br />
    <%= f.text_area :prompt, :rows=>4 %>
  </div>
  <div class="field">
    <%= f.label :yes_text %><br />
    <%= f.text_field :yes_text %>
  </div>
  <div class="field">
    <%= f.label :no_text %><br />
    <%= f.text_field :no_text %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tags/edit.html.erb
<h1>Editing tag</h1>

<%= render 'form' %>

<%= link_to 'Show', @tag %> |
<%= link_to 'Back', tags_path %>

app/views/tags/index.html.erb
<h1>Listing tags</h1>

<table>
  <tr>
    <th>Name</th>
    <th>Prompt</th>
    <th>Yes text</th>
    <th>No text</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @tags.each do |tag| %>
  <tr>
    <td><%= tag.name %></td>
    <td><%= tag.prompt %></td>
    <td><%= tag.yes_text %></td>
    <td><%= tag.no_text %></td>
    <td><%= link_to 'Show', tag %></td>
    <td><%= link_to 'Edit', edit_tag_path(tag) %></td>
    <td><%= link_to 'Destroy', tag, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Tag', new_tag_path %>

app/views/tags/new.html.erb
<h1>New tag</h1>

<%= render 'form' %>

<%= link_to 'Back', tags_path %>

app/views/tags/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Name:</b>
  <%= @tag.name %>
</p>

<p>
  <b>Prompt:</b>
  <%= @tag.prompt %>
</p>

<p>
  <b>Yes text:</b>
  <%= @tag.yes_text %>
</p>

<p>
  <b>No text:</b>
  <%= @tag.no_text %>
</p>


<%= link_to 'Edit', edit_tag_path(@tag) %> |
<%= link_to 'Back', tags_path %>