config/routes.rb
Ontology::Application.routes.draw do
  get "home/main"

  resources :tags

  resources :concepts

  root :to => 'concepts#index'

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Ontology" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <!-- For third-generation iPad with high-resolution Retina display: -->
    <!-- Size should be 144 x 144 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>

    <!-- For iPhone with high-resolution Retina display: -->
    <!-- Size should be 114 x 114 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>

    <!-- For first- and second-generation iPad: -->
    <!-- Size should be 72 x 72 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>

    <!-- For non-Retina iPhone, iPod Touch, and Android 2.1+ devices: -->
    <!-- Size should be 57 x 57 pixels -->
    <%= favicon_link_tag 'images/apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>

    <!-- For all other devices -->
    <!-- Size should be 32 x 32 pixels -->
    <%= favicon_link_tag 'images/favicon.ico', :rel => 'shortcut icon' %>
  </head>
  <body>

	<div class="navbar navbar-fixed-top">
      	<div class="navbar-inner">
        	<div class="container">
				<a class="btn btn-navbar" data-target=".nav-collapse" data-toggle="collapse">
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</a>

          		<a class="brand" href="<%= root_path %>"><%= content_for?(:title) ? yield(:title) : "Ontology" %></a>
				<div class="nav-collapse collapse">
	            <ul class="nav">
	              	<li><%= link_to 'New Concept', new_concept_path %></li>
					<li><!-- Button to trigger modal --><a href="#myModal" role="button" data-toggle="modal">Generate output</a></li>
				  <li class="dropdown">
				    <a class="dropdown-toggle" data-toggle="dropdown" href="#">
						<i class="icon-user"></i>
				        Greg Manson
				        <b class="caret"></b>
				      </a>
				    <ul class="dropdown-menu">
		              <li class="">
		                <a href="#">Log out</a>
		              </li>
				    </ul>
				  </li><%# .dropdown %>
				</ul><%# .nav %>
				<form class="navbar-search pull-right" action="<%= concepts_path %>" method="get">
	              <input name="search" type="text" class="search-query span3" placeholder="Search" data-provide="typeahead" data-source='<%= raw Concept.typeahead_array %>'>
	            </form>
				
	          </div><%# .nav-collapse collapse%>
        	</div>
      	</div>
    </div>


    <div class="container-fluid">
      <div class="row-fluid">
        <div class="span12">
          <%= yield %>
        </div>
      </div><!--/row-->

      <footer>
        <p> </p>
      </footer>

    </div> <!-- /container -->

    <!-- Javascripts
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <%= javascript_include_tag "application" %>

  </body>
</html>